# Database
spring.datasource.url=jdbc:mysql://localhost:3306/fitness_db
spring.datasource.username=root
spring.datasource.password=vishal#123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Security auto config ??? ???
spring.security.user.name=admin
spring.security.user.password=admin

# Open in view warning ??? ???
spring.jpa.open-in-view=false

# Server
server.port=8082